### ISSUE TITLE
App widget crash

### ISSUE THREAD

**Issue by alexthelion** [alexdantas/kure-music-player#1]
Hi
It seems that lock screen widget is not always working in your app.
I get this error:

```
08-30 23:19:59.379 29738-29738/com.android.systemui E/KeyguardHostView﹕ Error when trying to bind default AppWidget: java.lang.IllegalArgumentException: not a appwidget provider: ComponentInfo{/}
```

The strange that is in eclipse sometimes its working in debug mode and when i disconnect the phone from the pc it will stop from working. Any ideas?
I tryint to figure out how to add widget player to my app.

**Comment by alexdantas** [comment]
Hey, thanks for pointing this out. I'm glad you took interest on this small project of mine! :smile: 
Sorry for taking so long to answer you, this has been an exceptionally busy week for me,

You see, it was actually hard for me to figure out how to add this lock screen widget. I don't remember the specifics, but I only found like 2 different websites with tips on it and no complete source code.
I had to guess a few things here and there and it doesn't surprise me that it crashes.

I had noticed before that the widget would sometimes disappear, specially when you paused the music, but I didn't find that error you just pointed out.

So I have no idea why would this error happen, nor how could you fix it, sorry...
If you ever find out how to do it, could you please comment here? Thanks!

**Comment by alexthelion** [comment]
Hey,
I fixed it today.
i just added : System.exit(0);
to on destroy method and now its always working :)

2014-09-05 21:39 GMT+03:00 Alexandre Dantas notifications@github.com:

**Comment by alexdantas** [comment]
Hey @alexthelion , which `onDestroy()` method do you refer to?
The main menu?

**Comment by alexthelion** [comment]
Its not worked for me. I found that there is a problem with stopping the
player service its not always stopped when you finishing the app.

**Comment by alexdantas** [comment]
Yes, you're right.
I just added `System.exit(0)` when you press back twice at the main menu, and it still doesn't work.

I guess I'll have to dig deeper on the `Service` code... :pensive:

**Comment by alexthelion** [comment]
I try to fix it i hope it won't be hard... If i will succeed i will let you
know
